In [1]:
import numpy as np

In [28]:
a = np.array([[1,2,3]])
a

array([[1, 2, 3]])

In [29]:
a.shape

(1, 3)

In [30]:
# tranpose a to (1,3)
a = np.transpose(a)
a

array([[1],
       [2],
       [3]])

In [49]:
a.shape

(3, 1)

In [5]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [7]:
b.shape

(2, 2)

## Mimicking cost function


Theta shape is 2 * 1 while X shape is m * 2. Theoretically, X multiplies theta should give m * 1



In [45]:
theta = np.array([3,2])
theta.shape

(2,)

In [46]:
X = np.array([[1,3],[2,5],[9,4]])
X.shape

(3, 2)

In [47]:
X

array([[1, 3],
       [2, 5],
       [9, 4]])

In [50]:
hypo = np.dot(X, theta)
hypo

array([ 9, 16, 35])

In [52]:
# another one

In [68]:
t = np.array([3,2])
t.shape

(2,)

In [69]:
t

array([3, 2])

In [70]:
t =t.reshape((1,2))
t.shape

(1, 2)

In [71]:
t

array([[3, 2]])

In [86]:
haha = np.zeros(2)
haha.shape

(2,)

In [87]:
haha

array([0., 0.])

In [89]:
haha = haha.reshape((1,haha.size))
haha.shape

(1, 2)

In [90]:
haha

array([[0., 0.]])