## Implement sigmoid function

g(z) = 1/(1+e^-z)

In [2]:
import numpy as np

In [12]:
x = np.array([[1,0],[9,2]])

In [13]:
x*2

array([[ 2,  0],
       [18,  4]])

In [14]:
np.exp(x)

array([[2.71828183e+00, 1.00000000e+00],
       [8.10308393e+03, 7.38905610e+00]])

In [15]:
1/(1+np.exp(x))

array([[2.68941421e-01, 5.00000000e-01],
       [1.23394576e-04, 1.19202922e-01]])

## Test stack and concat

In [37]:
X = np.array([[4,5],[14,9],[29,3]])
X

array([[ 4,  5],
       [14,  9],
       [29,  3]])

In [38]:
m,n = X.shape


In [36]:
# Add a column of ones to X. The numpy function stack joins arrays along a given axis. 
# The first axis (axis=0) refers to rows (training examples) 
# and second axis (axis=1) refers to columns (features).
Xstack = np.stack([np.ones(6), X], axis=1)

ValueError: all input arrays must have the same shape

In [39]:
Xconcat = np.concatenate([np.ones((m, 1)), X], axis=1)

In [40]:
Xconcat

array([[ 1.,  4.,  5.],
       [ 1., 14.,  9.],
       [ 1., 29.,  3.]])

In [7]:
test1 = np.array([48,3,2])

In [10]:
test1.shape

(3,)

In [11]:
test1[0]

48

In [14]:
for i in range(3):
    print("hi" ,i)

hi 0
hi 1
hi 2


## Test theta size

In [17]:
init_theta = np.zeros(3+1)

In [18]:
init_theta.size

4